const TEMPLATES = [
    "{NEG_OPENER} {TRACKER} mods just {PUNISHMENT} for {OFFENSE} {?ASIDE}",
    "{NEG_OPENER} {TRACKER} staff just {PUNISHMENT} for {OFFENSE} {?ASIDE}",
    "BREAKING: {TRACKER} staff just {DID_SOMETHING_CRAZY}",
    "BREAKING: {TRACKER} just {DID_SOMETHING_CRAZY}",
    "BREAKING: {TRACKER} just announced they {DID_SOMETHING_CRAZY}",
    "Any way to get back into {TRACKER} after I got banned for {OFFENSE}? {?ASIDE}",
    "{TRACKER} rules are ridiculous. Just got suspended for {OFFENSE} {?ASIDE}",
    "When will the autobrr team make a replacement for {SAVE_US_AUTOBRR}?",
    "When is the autobrr team gonna finally give us a replacement for {SAVE_US_AUTOBRR}?",
    "{OPENER} {TRACKER} is now recruiting from {PLACE}",
    "{OPENER} {TRACKER} mods just left and joined {TRACKER}",
    "{REVEAL} {TRACKER} mods are secretly in charge of the subreddit",
    "{REVEAL} {TRACKER} is dying because the mods defected to {TRACKER}",
    "{REVEAL} I'm closing {TRACKER} because {CLOSING_REASON}",
    "{OPENER} {TRACKER} just announced they're going to start recruiting on {PLACE}",
    "{I_THINK} {TRACKER} will be cabal in {TIME}",
    "{I_THINK} {TRACKER} will be cabal in {TIME}",
    "{I_THINK} {TRACKER} is going to overtake {TRACKER}",
    "{I_THINK} {TRACKER} is about to overtake {TRACKER}",
];

const TOKENS = {
    TRACKER: [
        "Aither",
        "Aither",
        "Blutopia",
        "PTP",
        "PTP",
        "GGn",
        "MyAnonamouse",
        "ULCX",
        "RED",
        "OPS",
        "BHD",
        "BHD",
        "MTV",
        "BTN",
        "FNP",
        "FNP",
        "OTW",
        "HUNO",
        "LST",
        "seedpool",
        "seedpool"
    ],

    REVEAL: [
        "TELL-ALL EXPOSÉ:",
        "That's it, I'm spilling the beans.",
    ],

    CLOSING_REASON: [
        "I'm mad",
        "influencers stole all my money",
        "{TRACKER} stole all my staff",
        "/r/trackers mods stole all my money",
        "I was hacked by /r/trackers mods who are secretly agents of {TRACKER}"
    ],
        
    NEG_OPENER: [
        "HELP!",
        "The fuck?",
        "Ugh, I'm done.",
        "I can't believe this.",
        "Wow.",
        "Be careful:",
    ],

    OPENER: [
        "Guys,",
        "GUYS!!",
        "Did you hear?",
        "Woah:"
    ],

    PUNISHMENT: [
        "banned me",
        "chatbox muted me",
        "suspended me",
        "tree-banned me",
        "banned a user",
        "suspended a user",
        "revoked my upload rights",
        "revoked my download rights",
        "disabled my sparkles",
        "killed my parents",
        "deleted my seedbox",
        "froze all my BON",
        "deleted all my cross-seeds",
    ],

    OFFENSE: [
        "being TOO good at racing",
        "pronouncing UNIT3D as UNIT 3D",
        "pronouncing UNIT3D as United",
        "rebuilding my ZFS pool",
        "recommending ZFS",
        "seeding anime",
        "not seeding enough anime",
        "having a positive ratio",
        "using a seedbox",
        "vote manipulation and deception",
        "being nice to a corgi",
        "being rude to a thimble",
        "confusing spindrift with spindrifter",
        "calling them out on their racism",
        "posting a meme in the forums",
        "asking about freeleech",
        "posting a screenshot of the rules",
        "even THINKING about cabal",
        "submitting a help ticket",
        "trying to use the tag -Kitsune",
        "trying to use the tag -NTb",
        "trying to use the tag -DON",
        "cross-seeding their internals",
        "applying for Uploader",
        "applying to be an internal",
        "sending feet pics to mods",
        "not sending feet pics to mods",
        "calling you-know-who a femboy",
        "uploading Dailymotion fanres",
        "making bad remuxes",
        "making great remuxes",
        "not wearing a hat",
        "wearing a hat"
    ],

    ASIDE: [
        "(with no warning)",
        "(on my birthday)",
        "(I was top 10 in upload)",
        "(I had a 100TB seedsize)",
        "(after 6 years of membership)",
        "(right after I donated)",
        "(while I was sleeping)",
        "(during freeleech)",
        "(and invite trading)",
        "(and asking for invites)",
        "(and clogging up modq)",
        "(and using racial slurs)",
    ],

    DID_SOMETHING_CRAZY: [
        "deleted the tracker",
        "leaked their entire torrent database",
        "made anime uploads mandatory",
        "banned all anime",
        "reset everyone's ratio",
        "disabled seeding",
        "merged with IPT",
        "got banned from /r/OpenSignups",
        "decided to stop keeping backups",
        "got hacked by ex-{TRACKER} staff",
        "declared war on {TRACKER} staff",
        "decided to ban all {TRACKER} internals",
        "banned all {TRACKER} users",
        "got rid of all their internals",
        "reset everyone's upload stats",
        "forked UNIT3D",
        "made having BON illegal",
        "banned everyone in chatbox",
        "decided to pivot to debrid",
    ],

    PLACE: [
        "Seadex",
        "Seadex",
        "Seadex",
        "scene",
        "autobrr's Discord",
        "autobrr's GitHub issues",
        "Upload-Assistant's Discord",
        "Upload-Assistant's GitHub issues",
        "cross-seed's Discord",
        "cross-seed's GitHub issues",
        "Chaptarr's Discord",
        "TRaSH Guide's Discord",
        "TRaSH Guide's GitHub issues",
    ],

    SAVE_US_AUTOBRR: [
        "TRaSH guides",
        "Huntarr",
        "Seadex",
        "qui",
        "Linux",
        "IRC",
        "autobrr",
        "Deluge",
        "Unraid",
        "mergerFS",
        "Bazarr",
        "Readarr",
        "ZFS",
    ],

    TIME: [
        "less than 6 months",
        "1 year",
        "2 years",
        "3 years",
        "4 years",
        "5 years",
        "10 years",
    ],

    I_THINK: [
        "I think",
        "I genuinely think",
        "I strongly believe",
        "Theory:"
    ],

};
